In [12]:
# The first step of using numpy is to tell python to import it
import numpy as np

### 2.1 NumPy Arrays

**NumPy Array**
* An array is a data structure that stores values of same data type.
* While python lists can contain values corresponding to different data types, arrays in python can only contain values corresponding to the same data type.
* However python lists fail to deliver the performance required while computing large sets of numerical data. To address this issue we use NumPy arrays.
* We can create NumPy arrays by converting a list to an array.


In [13]:
# defining a list of different car companies or string elements
arr_str = ['Mercedes', 'BMW', 'Audi', 'Ferrari', 'Tesla', 'Mistubishi']

# defining a list of number of cylinders in car or numerical elements
arr_num = [5, 4, 6, 7, 3]

In [14]:
# connverting the list arr_str to a NumPy array
np_arr_str = np.array(arr_str)


# connverting the list arr_num to a NumPy array
np_arr_num = np.array(arr_num)

# checking the output
print('Numpy Array (arr_str): ',np_arr_str)
print('Numpy Array (arr_num): ',np_arr_num)

Numpy Array (arr_str):  ['Mercedes' 'BMW' 'Audi' 'Ferrari' 'Tesla' 'Mistubishi']
Numpy Array (arr_num):  [5 4 6 7 3]


The resuts look similar to a list but arr_str and arr_num have been converted to NumPy arrays. Let's check the data type to confirm this.

In [15]:
# printing the data type of lists
print('Data type of arr_str: ',type(arr_str))
print('Data type of arr_num: ',type(arr_num))

# printing the data type after conversion of lists to array
print('Data type of np_arr_str: ',type(np_arr_str))
print('Data type of np_arr_num: ',type(np_arr_num))

Data type of arr_str:  <class 'list'>
Data type of arr_num:  <class 'list'>
Data type of np_arr_str:  <class 'numpy.ndarray'>
Data type of np_arr_num:  <class 'numpy.ndarray'>


* The above output confirms that both the lists were successfully converted to arrays

**NumPy Matrix**

* A matrix is a two-dimensional data structure where elements are arranged into rows and columns.
* A matrix can be created by using list of lists

In [16]:
# let's say we have information of different number of cylinders in a car and we want to display them in a matrix format
matrix = np.array([[1,2,1],[4,5,9],[1,8,9]])
print(matrix)
# matrix transpose or .T
matrix_transpose = matrix.transpose()
print('matrix transpose \n', matrix_transpose)

[[1 2 1]
 [4 5 9]
 [1 8 9]]
matrix transpose 
 [[1 4 1]
 [2 5 8]
 [1 9 9]]


In [17]:
print('Data type of matrix: ',type(matrix))

Data type of matrix:  <class 'numpy.ndarray'>


* We see that all the NumPy objects have data type as ndarray

### 2.2 NumPy Functions

**There are different ways to create NumPy arrays using the functions available in NumPy library**

**Using np.arange() function**
* The np.arange() function returns an array with evenly spaced elements as per the interval. The interval mentioned is half-opened i.e. start is included but stop is excluded.
* It has the following paramaters:
  * start : start of interval range. By default start = 0
  * stop  : end of interval range
  * step  : step size of interval. By default step size = 1

In [18]:
arr2  = np.arange(start = 0, stop = 10) # 10 will be excluded from the output
print(arr2)

# or

arr2  = np.arange(0, 10)
print(arr2)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]


In [19]:
# adding a step size of 5 to create an array
arr3  = np.arange(start = 0, stop = 20, step = 5)
arr3

array([ 0,  5, 10, 15])

**Using np.linspace() function**
* The np.linspace() function returns numbers which are evenly distributed with respect to interval. Here the start and stop both are included.            
*It has the following parameters:              
 * start: start of interval range. By default start = 0
 * stop: end of interval range
 * num : No. of samples to generate. By default num = 50

In [20]:
matrix2 = np.linspace(0,5) # by default 50 evenly spaced values will be generated between 0 and 5
matrix2
matrix_test = np.linspace(10, 20, 20)
matrix_test

array([10.        , 10.52631579, 11.05263158, 11.57894737, 12.10526316,
       12.63157895, 13.15789474, 13.68421053, 14.21052632, 14.73684211,
       15.26315789, 15.78947368, 16.31578947, 16.84210526, 17.36842105,
       17.89473684, 18.42105263, 18.94736842, 19.47368421, 20.        ])

**How are these values getting generated?**

The step size or the difference between each element will be decided by the following formula:

**(stop - start) / (total elements - 1)**

So, in this case:
(5 - 0) / 49 = 0.10204082

The first value will be 0.10204082, the second value will be 0.10204082 + 0.10204082, the third value will be 0.10204082 + 0.10204082 +0.10204082, and so on.

In [21]:
# generating 10 evenly spaced values between 10 and 20
matrix3 = np.linspace(10,20,10)
matrix3

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

**Similarly we can create matrices using the functions available in NumPy library**

**Using np.zeros()**

* The np.zeros() is a function for creating a matrix and performing matrix operations in NumPy.
* It returns a matrix filled with zeros of the given shape.
* It has the following parameters:    
  * shape : Number of rows and columns in the output matrix.
  * dtype: data type of the elements in the matrix, by default the value is set to `float`.

In [22]:
matrix4 = np.zeros([3,5])
matrix4
# 2d matrix
np.zeros([3,4,10])



array([[[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]]])

**Using np.ones()**

* The np.ones() is another function for creating a matrix and performing matrix operations in NumPy.
* It returns a matrix of given shape and type, filled with ones.
* It has the following parameters:  
  * shape : Number of rows and columns in the output matrix.
  * dtype: data type of the elements in the matrix, by default the value is set to `float`.

In [23]:
matrix5 = np.ones([3,5])
matrix5

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

**Using np.eye()**
* The np.eye() is a function for creating a matrix and performing matrix operations in NumPy.
* It returns a matrix with ones on the diagonal and zeros elsewhere.
* It has the following parameters:
  * n: Number of rows and columns in the output matrix
  * dtype: data type of the elements in the matrix, by default the value is set to `float`.

In [24]:
matrix6 = np.eye(5)
matrix6
# np.eye(6,3)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

**We can also convert a one dimension array to a matrix. This can be done by using the np.reshape() function.**

* The shape of an array basically tells the number of elements and dimensions of the array. Reshaping a Numpy array simply means changing the shape of the given array.
* By reshaping an array we can add or remove dimensions or change number of elements in each dimension.
* In order to reshape a NumPy array, we use the reshape method with the given array.
* **Syntax:** array.reshape(shape)
  * shape: a tuple given as input, the values in tuple will be the new shape of the array.

In [25]:
# defining an array with values 0 to 9
arr4 = np.arange(0, 10)
arr4

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
# reshaping the array arr4 to a 2 x 5 matrix
arr4_reshaped = arr4.reshape((2,5))
arr4_reshaped

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [27]:
arr4

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
# reshaping the array arr4 to a 2 x 6 matrix
arr4.reshape((2,6))

ValueError: cannot reshape array of size 10 into shape (2,6)

* This did not work because we have 10 elements which we are trying to fit in a 2 X 6 shape which will require 12 elements.

**NumPy can also perform a large number of different mathematical operations and it provides different functions to do so.**

NumPy provides:
1. Trigonometric functions
2. Exponents and Logarithmic functions
3. Functions for arithmetic operations between arrays and matrices

**Trigonometric functions**

In [ ]:
print('Sine Function:',np.sin(4))
print('Cosine Function:',np.cos(4))
print('Tan Function',np.tan(4))

* Exponents

**Exponents and Logarithmic functions**

In [ ]:
np.exp(2)
np.exp(25.252502502)


In [ ]:
arr5 = np.array([2,4,6])
np.exp(arr5)

* Logarithms

In [ ]:
# by default NumPy takes the base of log as e
np.log(2)
np.log(7.38905609893065)
np.log(92687782248.27428)

In [ ]:
np.log(arr5)

In [ ]:
## log with base 10
np.log10(8)

**Arithmetic Operations on arrays**

In [ ]:
# arithmetic on lists

l1 = [1,2,3]
l2 = [4,5,6]
print(l1+l2)
# this does not behave as you would expect!


In [ ]:
# we can +-*/ arrays together

# defining two arrays
arr7 = np.arange(1,6)
print('arr7:', arr7)

arr8 = np.arange(3,8)
print('arr8:', arr8)

In [ ]:
print('Addition: ',arr7+arr8)
print('Subtraction: ',arr8-arr7)
print('Multiplication:' , arr7*arr8)
print('Division:', arr7/arr8)
print('Inverse:', 1/arr7)
print('Powers:', arr7**arr8) # in python, powers are achieved using **, NOT ^!!! ^ does something completely different!
a = 5 # Binary: 0101
b = 3 # Binary: 0011
result = a ^ b # Binary: 0110 XOR operation
print(result)

**Operations on Matrices**

In [57]:
matrix7 = np.arange(1,10).reshape(3,3)
print(matrix7)

matrix8 = np.eye(3)
print(matrix8)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [58]:
print('Addition: \n', matrix7+matrix8)
print('Subtraction: \n ', matrix7-matrix8)
print('Multiplication: \n', matrix7*matrix8)
print('Division: \n', matrix7/matrix8)

Addition: 
 [[ 2.  2.  3.]
 [ 4.  6.  6.]
 [ 7.  8. 10.]]
Subtraction: 
  [[0. 2. 3.]
 [4. 4. 6.]
 [7. 8. 8.]]
Multiplication: 
 [[1. 0. 0.]
 [0. 5. 0.]
 [0. 0. 9.]]
Division: 
 [[ 1. inf inf]
 [inf  5. inf]
 [inf inf  9.]]


/tmp/ipython-input-58-2604038799.py:4: RuntimeWarning: divide by zero encountered in divide
  print('Division: \n', matrix7/matrix8)


* RuntimeWarning: Errors which occur during program execution(run-time) after successful compilation are called run-time errors.
* One of the most common run-time error is division by zero also known as Division error.
* Due to division by zero error, we are getting inf (infinity) values because 1/0 is not a defined operation.

**Linear algebra matrix multiplication**

In [60]:
matrix9 = np.arange(1,10).reshape(3,3)
print('First Matrix: \n',matrix9)

matrix10 = np.arange(11,20).reshape(3,3)
print('Second Matrix: \n',matrix10)
print('')
# taking linear algebra matrix multiplication (some may have heard this called the dot product)
print('Multiplication: \n', matrix9 @ matrix10)

First Matrix: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Second Matrix: 
 [[11 12 13]
 [14 15 16]
 [17 18 19]]

Multiplication: 
 [[ 90  96 102]
 [216 231 246]
 [342 366 390]]


### Matrix multiplication of a 3 x 3 two matrices.
- The rule of multiplying matrix A to B is that the columns of A should be equal to the rows of B.
- In the below example `matrix_a` is a 1 x _`3`_ matrix, and `matrix_b` is a _`3`_ x 1 matrix. Hence it's a valid input to multiply.

In [61]:
matrix_a = np.array([3, 1, 4])
matrix_b = np.array([[4,3],[2, 5],[6, 8]])
print(matrix_a @ matrix_b)

[38 46]


### Invalid matrix multiplication example
- In the below example we try to multiply `matrix_b` with `matrix_a` and that is 3 x _`1`_ . 1 x _`3`

`this will cause an error`

In [62]:
print(matrix_b @ matrix_a)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 2)

In [63]:
x = 31
y = 2
mat_x = round(x / 2)
mat_y = 2
print(round(21 / 2))
# matrix_test_a = np.arange(1, x).reshape(mat_x, mat_y)
matrix_test_a

10


NameError: name 'matrix_test_a' is not defined

In [64]:
bags = np.arange(1, 11)
coin_bags = np.zeros(10)
bag_with_marker = 6

coin_bags[bag_with_marker - 1] = 1
# coin_bags[bag_with_marker - 2] = 1
print('bags (1 x 10) ->', bags)
print('weights (1 x 10) ->', coin_bags)
bags @ coin_bags

bags (1 x 10) -> [ 1  2  3  4  5  6  7  8  9 10]
weights (1 x 10) -> [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]


np.float64(6.0)

**Transpose of a matrix**

In [65]:
print(matrix9)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [66]:
# taking transpose of matrix
np.transpose(matrix9)

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [78]:
# another way of taking a transpose
matrix9.T
matrix10 = np.arange(0, 15).reshape(3,5)
print(matrix10)
print(matrix10.T)
matrix10 @ matrix10.T

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


array([[ 30,  80, 130],
       [ 80, 255, 430],
       [130, 430, 730]])

**Function to find minimum and maximum values**

In [ ]:
print(matrix9)

In [ ]:
print('Minimum value: ',np.min(matrix9))

In [ ]:
print('Maximum value: ',np.max(matrix9))

**Function to generate random samples**

**Using np.random.rand function**

* The np.random.rand returns a random NumPy array whose element(s) are drawn randomly from the uniform distribution over [0,1). (including 0 but excluding 1).
* **Syntax** - np.random.rand(d0,d1)
  * d0,d1 – It represents the dimension of the required array given as int, where d1 is optional.

In [ ]:
# Generating random values in an array
rand_mat = np.random.rand(5)
print(rand_mat)

In [ ]:
# * Generating random values in a matrix
rand_mat = np.random.rand(5,5) # uniform random variable
print(rand_mat)

**Using np.random.randn function**

* The np.random.randn returns a random numpy array whose sample(s) are drawn randomly from the standard normal distribution (Mean as 0 and standard deviation as 1)

* **Syntax** - np.random.randn(d0,d1)
  * d0,d1 – It represents the dimension of the output, where d1 is optional.

In [ ]:
# Generating random values in an array
rand_mat2 = np.random.randn(5)
print(rand_mat2)

In [ ]:
# Generating random values in a matrix
rand_mat2 = np.random.randn(5,5)
print(rand_mat2)

In [ ]:
# Let's check the mean and standard deviation of rand_mat2
print('Mean:',np.mean(rand_mat2))
print('Standard Deviation:',np.std(rand_mat2))

*  We observe that the mean is very close to 0 and standard deviation is very close to 1.

**Using np.random.randint function**

* The np.random.randint returns a random numpy array whose element(s) are drawn randomly from low (inclusive) to the high (exclusive) range.

* **Syntax** - np.random.randint(low, high, size)

  * low – It represents the lowest inclusive bound of the distribution from where the sample can be drawn.
  * high – It represents the upper exclusive bound of the distribution from where the sample can be drawn.
  * size – It represents the shape of the output.

In [ ]:
# Generating random values in an array
rand_mat3 = np.random.randint(1,5,10)
print(rand_mat3)

In [30]:
# Generating random values in a matrix
rand_mat3 = np.random.randint(1,10,[5,5])
print(rand_mat3)

[[1 3 9 9 4]
 [1 4 2 9 2]
 [2 9 7 3 7]
 [3 5 1 4 5]
 [1 1 9 9 1]]


### 2.3 Accessing the entries of a Numpy Array

In [31]:
# let's generate an array with 10 random values
rand_arr = np.random.randn(10)
print(rand_arr)

[-1.18976097  0.24774721  2.26993987 -1.0673779  -0.70718703  1.48307425
  0.80773649 -0.24401457  2.35022609 -0.13292358]


* Accessing one element from an array

In [32]:
# accessing the 6 th entry of rand_arr
print(rand_arr[6])

0.8077364871631796


* Accessing multiple elements from an array

In [33]:
# we can access multiple entries at once using
print(rand_arr[4:9])

[-0.70718703  1.48307425  0.80773649 -0.24401457  2.35022609]


In [34]:
# we can also access multiple non-consecutive entries using np.arange
print('Index of values to access: ',np.arange(3,10,3))
print(rand_arr[np.arange(3,10,3)])

Index of values to access:  [3 6 9]
[-1.0673779   0.80773649 -0.13292358]


**Accessing arrays using logical operations**

In [35]:
print(rand_arr)

[-1.18976097  0.24774721  2.26993987 -1.0673779  -0.70718703  1.48307425
  0.80773649 -0.24401457  2.35022609 -0.13292358]


In [36]:
rand_arr>0

array([False,  True,  True, False, False,  True,  True, False,  True,
       False])

In [37]:
# accessing all the values of rand_arr which are greater than 0
print('Values greater than 0: ',rand_arr[rand_arr>0])

# accessing all the values of rand_arr which are less than 0
print('Values less than 0: ',rand_arr[rand_arr<0])

Values greater than 0:  [0.24774721 2.26993987 1.48307425 0.80773649 2.35022609]
Values less than 0:  [-1.18976097 -1.0673779  -0.70718703 -0.24401457 -0.13292358]


**Accessing the entries of a Matrix**

In [38]:
# let's generate an array with 10 random values
rand_mat = np.random.randn(5,5)
print(rand_mat)

[[-8.36398198e-01 -5.29761591e-01 -5.00817511e-01 -4.98236320e-01
   5.14245081e-01]
 [-3.62004751e-01  5.30531819e-01  8.74234151e-01  1.22788985e+00
   7.99400463e-01]
 [ 2.78180838e+00 -3.29769327e-01  5.03988155e-01 -5.54375925e-01
   7.90778213e-04]
 [-8.37249541e-02  5.73031024e-01  1.80208968e-03 -5.86626497e-01
   1.72409611e+00]
 [-1.23817832e-01  5.30967811e-01 -1.55060362e+00 -5.46399502e-01
  -1.14604610e+00]]


In [39]:
# acessing the second row of the rand_mat
rand_mat[1]

array([-0.36200475,  0.53053182,  0.87423415,  1.22788985,  0.79940046])

In [40]:
# acessing third element of the second row
print(rand_mat[1][2])

#or

print(rand_mat[1,2])

0.8742341505760568
0.8742341505760568


In [41]:
# accessing first two rows with second and third column
print(rand_mat[0:2,1:3])

[[-0.52976159 -0.50081751]
 [ 0.53053182  0.87423415]]


**Accessing matrices using logical operations**

In [42]:
print(rand_mat)

[[-8.36398198e-01 -5.29761591e-01 -5.00817511e-01 -4.98236320e-01
   5.14245081e-01]
 [-3.62004751e-01  5.30531819e-01  8.74234151e-01  1.22788985e+00
   7.99400463e-01]
 [ 2.78180838e+00 -3.29769327e-01  5.03988155e-01 -5.54375925e-01
   7.90778213e-04]
 [-8.37249541e-02  5.73031024e-01  1.80208968e-03 -5.86626497e-01
   1.72409611e+00]
 [-1.23817832e-01  5.30967811e-01 -1.55060362e+00 -5.46399502e-01
  -1.14604610e+00]]


In [43]:
# accessing all the values of rand_mat which are greater than 0
print('Values greater than 0: \n ',rand_mat[rand_mat>0])

# accessing all the values of rand_mat which are less than 0
print('Values less than 0: \n',rand_mat[rand_mat<0])

Values greater than 0: 
  [5.14245081e-01 5.30531819e-01 8.74234151e-01 1.22788985e+00
 7.99400463e-01 2.78180838e+00 5.03988155e-01 7.90778213e-04
 5.73031024e-01 1.80208968e-03 1.72409611e+00 5.30967811e-01]
Values less than 0: 
 [-0.8363982  -0.52976159 -0.50081751 -0.49823632 -0.36200475 -0.32976933
 -0.55437593 -0.08372495 -0.5866265  -0.12381783 -1.55060362 -0.5463995
 -1.1460461 ]


**Modifying the entries of an Array**

In [44]:
print(rand_arr)

[-1.18976097  0.24774721  2.26993987 -1.0673779  -0.70718703  1.48307425
  0.80773649 -0.24401457  2.35022609 -0.13292358]


In [45]:
# let's change some values in an array!
# changing the values of index value 3 and index value 4 to 5
rand_arr[3:5] = 5
print(rand_arr)

[-1.18976097  0.24774721  2.26993987  5.          5.          1.48307425
  0.80773649 -0.24401457  2.35022609 -0.13292358]


In [46]:
# changing the values of index value 0 and index value 1 to 2 and 3 respectively
rand_arr[0:2] = [2,3]
print(rand_arr)

[ 2.          3.          2.26993987  5.          5.          1.48307425
  0.80773649 -0.24401457  2.35022609 -0.13292358]


In [47]:
# modify entries using logical references
rand_arr[rand_arr>0] = 65
rand_arr

array([65.        , 65.        , 65.        , 65.        , 65.        ,
       65.        , 65.        , -0.24401457, 65.        , -0.13292358])

**Modifying the entries of a Matrix**

In [48]:
print(rand_mat3)

[[1 3 9 9 4]
 [1 4 2 9 2]
 [2 9 7 3 7]
 [3 5 1 4 5]
 [1 1 9 9 1]]


In [49]:
# changing the values of the 4th and 5th element of the second and third rows of the matrix to 0
print('Matrix before modification: \n',rand_mat3)
rand_mat3[1:3,3:5] = 0
print('Matrix after modification: \n',rand_mat3)

Matrix before modification: 
 [[1 3 9 9 4]
 [1 4 2 9 2]
 [2 9 7 3 7]
 [3 5 1 4 5]
 [1 1 9 9 1]]
Matrix after modification: 
 [[1 3 9 9 4]
 [1 4 2 0 0]
 [2 9 7 0 0]
 [3 5 1 4 5]
 [1 1 9 9 1]]


In [50]:
# extracting the first 2 rows and first 3 columns from the matrix
sub_mat = rand_mat[0:2,0:3]
print(sub_mat)

[[-0.8363982  -0.52976159 -0.50081751]
 [-0.36200475  0.53053182  0.87423415]]


In [51]:
# changing all the values of the extracted matrix to 3
sub_mat[:] = 3
print(sub_mat)

[[3. 3. 3.]
 [3. 3. 3.]]


In [52]:
# what happened to rand_mat when we change sub_mat?
rand_mat

array([[ 3.00000000e+00,  3.00000000e+00,  3.00000000e+00,
        -4.98236320e-01,  5.14245081e-01],
       [ 3.00000000e+00,  3.00000000e+00,  3.00000000e+00,
         1.22788985e+00,  7.99400463e-01],
       [ 2.78180838e+00, -3.29769327e-01,  5.03988155e-01,
        -5.54375925e-01,  7.90778213e-04],
       [-8.37249541e-02,  5.73031024e-01,  1.80208968e-03,
        -5.86626497e-01,  1.72409611e+00],
       [-1.23817832e-01,  5.30967811e-01, -1.55060362e+00,
        -5.46399502e-01, -1.14604610e+00]])

In [53]:
# to prevent this behavior we need to use the .copy() method when we assign sub_mat
# this behavior is the source of MANY errors for early python users!!!

rand_mat = np.random.randn(5,5)
print(rand_mat)
sub_mat = rand_mat[0:2,0:3].copy()
sub_mat[:] = 3
print(sub_mat)
print(rand_mat)

[[-0.40202622 -0.55719856  2.62447113 -0.52422798  1.30873532]
 [ 1.37401761  1.02522722 -1.58956287  0.40900518  0.55818559]
 [ 0.88991917 -0.7581191   0.95172101  1.70030541 -1.9440658 ]
 [ 0.10625923 -0.15860917 -0.26272368 -0.80625337 -1.05717507]
 [ 1.25717346  1.80970819 -0.28702303 -0.14693215  0.3575782 ]]
[[3. 3. 3.]
 [3. 3. 3.]]
[[-0.40202622 -0.55719856  2.62447113 -0.52422798  1.30873532]
 [ 1.37401761  1.02522722 -1.58956287  0.40900518  0.55818559]
 [ 0.88991917 -0.7581191   0.95172101  1.70030541 -1.9440658 ]
 [ 0.10625923 -0.15860917 -0.26272368 -0.80625337 -1.05717507]
 [ 1.25717346  1.80970819 -0.28702303 -0.14693215  0.3575782 ]]


### 2.4 Saving and Loading a NumPy array

**Let's save some NumPy objects on the disk for use later!**

In [54]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [55]:
# creating a random matrices
randint_matrix1 = np.random.randint(1,10,10).reshape(2,5)
print(randint_matrix1)
print('')
randint_matrix2 = np.random.randint(10,20,10).reshape(2,5)
print(randint_matrix2)

[[9 3 5 6 8]
 [2 5 9 3 9]]

[[10 12 12 13 14]
 [16 18 13 17 13]]


**Using np.save() function**

In [56]:
np.save('/content/drive/MyDrive/Python Course/saved_file_name',randint_matrix1)

FileNotFoundError: [Errno 2] No such file or directory: '/content/drive/MyDrive/Python Course/saved_file_name.npy'

**Using np.savez() function**

In [ ]:
np.savez('/content/drive/MyDrive/Python Course/multiple_files',randint_matrix1=randint_matrix1,randint_matrix2=randint_matrix2)

* The files will be saved in the directory where the Jupyter Notebook is located.
* With np.save() function, we can save an array/matrix to a NumPy .npy format.
* np.savez() function has an advantage over np.save() function because with np.savez(), we can store several arrays/matrices into a single file in uncompressed .npz format.

In [ ]:
# now let's load it
loaded_arr = np.load('/content/drive/MyDrive/Python Course/saved_file_name.npy')
loaded_multi = np.load('/content/drive/MyDrive/Python Course/multiple_files.npz')

print(loaded_arr)
print('')
print(loaded_multi)

* We see that .npy file has been loaded but the .npz file is returning a memory location.
* Let's see how to load the values stored in .npz file.

In [ ]:
print('1st Matrix: \n',loaded_multi['randint_matrix1'])
print('2nd Matrix: \n',loaded_multi['randint_matrix2'])

new_matrix  = loaded_multi['randint_matrix1']
print('New Matrix: \n',new_matrix)

In [ ]:
# we can also save/load text files...but only single variables
np.savetxt('/content/drive/MyDrive/Python Course/text_file_name.txt',randint_matrix1,delimiter=',')
rand_mat_txt = np.loadtxt('/content/drive/MyDrive/Python Course/text_file_name.txt',delimiter=',')
print(randint_matrix1)
print('')
print(rand_mat_txt)

In [ ]:
## Power operations